version: "3.7"

services: 

    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
        container_name: sql-server-2019
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=passworD142!
            - MSSQL_PID=Developer
        ports: 
            - "1433:1433"
        volumes: 
            - ./data/data:/var/opt/mssql/data
            - ./data/log:/var/opt/mssql/log
            - ./data/secrets:/var/opt/mssql/secrets
