version: "3.7"

services: 
    show-env:
        env_file: 
         - ./config/pro.env

    log-server:
        ports: 
            - "${LOG_SERVER_PORT}:80"
    
    restify-server: 
        ports: 
            - "${RESTIFY_SERVER_PORT}:80"

secrets:
    test-secrets:
        file: ./config/secrets-pro.json