version: "3.7"

x-labels: &app-net
    networks:
        - app-net

services: 
    show-env:
        image: show-env
        secrets:
         - source: test-secrets
           target: /src/config/secrets.json

    log-server:
        image:  log-server
        <<: *app-net
    
    restify-server: 
        image: restify-server
        depends_on: 
            - log-server
        <<: *app-net

networks:
    app-net:
        external:
            name: log-test-nat
