version: "3.7"

services: 
    test-app:
        ports: 
            - target: 80
              mode: host
        deploy:
            mode: global

    poke-app:
        ports:
            - "8888:80"
        deploy:
            replicas: 6

networks:
    app-net:
        name: update-rollback-network