version: "3.7"

x-labels: &app-net
  networks:
    - app-net

x-labels: &deploy
  deploy:
    replicas: 2
    resources:
      limits:
        cpus: "0.20"
        memory: 100M

services:
  show-env:
    image: show-env
    secrets:
      - source: test-secrets
        target: /src/config/secrets.json

  health-check-server:  
    image: health-check-server:v2
    ports: 
      - "8003:80"
    depends_on: 
      - log-server
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 1m30s
    <<: *app-net
    <<: *deploy

  log-server:
    image:  log-server
    ports: 
      - "8001:80"
    <<: *app-net
    <<: *deploy

  restify-server:
    image: restify-server
    depends_on: 
        - log-server
    <<: *app-net
    <<: *deploy     

networks:
  app-net:
    external: true
    name: swarm-test-net

secrets:
  test-secrets:
    file: ./config/secrets.json
 