version: "3.7"

services:
  timewriter:
    image: timewriter
    depends_on: 
      - fluentd
    logging:
      driver: "fluentd"
      options:
        tag: "logging-test.{{.ImageName}}"
    
  fluentd: 
    image: fluent/fluentd:v1.11-1
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment: 
      - FLUENT_CONF=fluent.conf
