version: "3.7"

services: 

    log-server:
        image:  log-server
        ports: 
            - "8003-8010:80"
        networks:
            - app-net
    
    restify-server: 
        image: restify-server
        ports: 
            - "8002:80"
        depends_on: 
            - log-server
        networks:
            - app-net
            
networks:
    app-net:
        external:
            name: log-test-nat

